# Generated by Django 5.1.2 on 2024-10-19 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_auth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eventos',
        ),
    ]
