# Generated by Django 5.1.2 on 2024-10-20 21:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='imagen',
            field=models.ImageField(default='static/post_default.png', upload_to='imagenes/'),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='comment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='posts',
            name='slug',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
