# Generated by Django 5.1.2 on 2024-10-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_categorias_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='slug',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
