# Generated by Django 5.1.2 on 2024-10-21 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_categorias_imagen_comentarios_likes_alter_posts_slug'),
        ('blog', '0003_alter_posts_slug'),
    ]

    operations = [
    ]
