# Generated by Django 5.1.2 on 2024-10-20 07:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_posts_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='comment_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
