# Generated by Django 5.1.2 on 2024-10-23 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_categorias_imagen_alter_posts_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
