# Generated by Django 5.1.2 on 2024-10-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_categorias_imagen_alter_posts_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario_personalizado',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
