# Generated by Django 5.1.2 on 2024-10-23 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_posts_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='news'),
        ),
    ]
