# Generated by Django 5.1.2 on 2024-10-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='news'),
        ),
        migrations.AddField(
            model_name='Usuario_personalizado',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
